### ISSUE TITLE
Missing feature: translation

### ISSUE THREAD

**Issue by jimblue** [naucon/grav-plugin-cookieconsent#1]
Hi!

Is it possible to add translation to the plugin?

On multilingual website it's a problem actually.

Thank you

**Comment by naucon** [comment]
Hi,

I added a `languages.yaml` with translations for english, french, spanish, german and italian.

Translations will be used if no `content_message`, `content_dismiss`, `content_link` or `content_href` are defined in `cookieconsent.yaml`.

56d461d5902747c9f58f5a63f89fc6fb1af4f861

May took some days until the updates is available over the grav package manager.

**Comment by jimblue** [comment]
That's great! Thank you @naucon 😄 !
