### ISSUE TITLE
Cannot to set relative link to policy

### ISSUE THREAD

**Issue by m-ochyra** [naucon/grav-plugin-cookieconsent#3]
Cannot save link like this: /polityka-cookies.

**Comment by GittiHab** [comment]
Same problem... if I have time I will create PR but I wouldn't mind if someone else does it before me ;)

**Comment by naucon** [comment]
@m-ochyra @GittiHab have a look at this release at https://github.com/naucon/grav-plugin-cookieconsent/releases/tag/0.3.0

> Changed the validation for policy link to be less strict to allow absolute as well as relative URl and path (commit 4b259296e782e9309ac7621f0911a9e320d0d397)
