### ISSUE TITLE
Enabled, but not working

### ISSUE THREAD

**Issue by kees-closed** [naucon/grav-plugin-cookieconsent#7]
I've installed the plugin, enabled it, but nothing shows up. As far as I understand your README.md, just enabling it should be enough. Could this be a bug? I'm using the latest Grav (1.4.6).

**Comment by naucon** [comment]
Hi @AquaL1te,

the plugin is working fine with Grav 1.4.6. Likely it's a problem of the theme.
Test the pugin with the default theme (Quark) to make sure.

The plugin hooks into the grav asset manager (https://learn.getgrav.org/themes/asset-manager). Some themes haven't (properbly) integrated the assets manager and therefore do not work.

Have a look at the following required elements in the base theme. Without them the plugin will not work.

```
{{ assets.css() }}
{{ assets.js() }}
```

**Comment by kees-closed** [comment]
You're right! After some closer inspection I saw that CSP was blocking the plugin. It works now! Sorry for that.

Adding this below in my Apache vhost allows the plugin the function.
```
style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; \
script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com;
```

**Comment by naucon** [comment]
Hi @AquaL1te have a look at the new release. Now you can choose between includes from CDN or local.
https://github.com/naucon/grav-plugin-cookieconsent/releases/tag/0.4.0
